#!/usr/bin/env bash
#   Create a file /var/run/myscript.pid containing the script PID.
#   write msg upon receiving or not  a SIGINT or sigterm
#   Deletes the file /var/run/myscript.pid and terminates 
#+  upon recevng SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
