#!/usr/bin/env bash
# print FizzBuzz when the nbr is a multiple of 3 
# and 5 fizz for 3
for ((n=1;n<=100;n++))
do
    if ((n % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((n % 3 == 0))
    then
        echo "Fizz"
    elif ((n % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$n"
    fi
done
