#!/usr/bin/env bash
# prints a msg 10 times using while loop and on the 9th iteration hi

i=1

while [ "$i" -lt 11 ]; do
  echo "Best School"
  
  # print Hi when i is 9
  if [ "$i" -eq 9 ]; then
    echo "Hi"
  fi

  ((i++))
done

