#!/usr/bin/env bash
# four bad luck, eight is your chance

i=1

while [ "$i" -lt 11 ]; do

  # if four bad luck elif eight good luck
  if [ "$i" -eq 4 ]; then
    echo "bad luck"
  elif [ "$i" -eq 8 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((i++))
done
