#!/usr/bin/env bash
# alx  checker

file="school"

# checks if it  exists
if [ -e "$file" ]; then

  echo "school file exists"

  # checks empty files
  if [ ! -s "$file" ]; then
    echo "school file is empty"

    # checks if file is a regular file
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  

  else

    echo "school file is not empty"

    # checks the file regular or not
    if [ -f "$file" ]; then
      echo "school is a regular file"
    fi  
  
  fi

else
  
  echo "school file does not exist"

fi
